### ISSUE TITLE
JW alternate images support

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#114]
Add support for JW Player alternate media images.

## Scope
- Use configured image label for 
  - Homepage Shelves
  - Library 
  - Live Channel 
  - Series
  - Movie
- Fallback to poster if image is not available

## Out-of-scope 
- Shelf aspect ratio support (e.g. vertical images) --> Ticket #152

## Customer workflow 
- Default is the poster image, which is always there and auto generated
- Set custom image labels on config & media level: 
   - `backgroundImage`
   - `channelLogoImage`
- Set custom shelf labels on config & playlist level 
  -  `shelfImage`
  

### Homepage shelves
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/42120041/187531087-91c5218e-616c-48f4-b1b8-00ab92f1d4cd.png">

### Library page
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/42120041/187531003-c6dcded3-81c7-4bc3-8472-483e13d5e10c.png">

### Movie page
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/42120041/187530863-663b44d4-f187-4026-87c5-d4e0da6ab385.png">

### Series Page
<img width="1973" alt="image" src="https://user-images.githubusercontent.com/42120041/187531578-9e9724e4-1fde-4375-aa8f-097920d37c5a.png">

### Live Page
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/42120041/187530970-451e8606-05f8-481d-a0b3-f80e8971d06b.png">

**Comment by marcovandeveen** [comment]
Alternative considered: 
1. Hardcoded labels
2. Custom parameters like 'shelf_image_label' on playlist and media objects
3. App config settings, e.g. image label on shelf
4. Image service configuration

We have chosen option 2
- Allows for label reuse
- Provide flexibility. E.g. easy for partners and customers to introduce new labels. E.g. 'rokuIimageLabel'
- Easier to reuse app configs across the platforms, as app config focus on content, not on layout.

**Comment by marcovandeveen** [comment]
@dbudzins @ChristiaanScheermeijer Could you review the updated ticket?

**Comment by ChristiaanScheermeijer** [comment]
@marcovandeveen I have doubts about the choice for shelves on the homepage:

- Set custom shelf labels on playlist level
  - shelfImageLabel
  - shelfImageAspectRatio

The `shelfImageLabel` would work because it doesn't impact the layout, but the `shelfImageAspectRatio` does. The shelves on the homepage are dynamically rendered, and the playlist is only fetched when visible. This means that we need to calculate the shelf height in advance.
