### ISSUE TITLE
Dynamic configuration as part of easy deployment instructions

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#134]
To get started we're forwarding people to these docs: 
- Easy deployment
- Enable dynamic configuration (from JW Dashboard)

Suggestion: make 'enable dynamic configuration' part of the easy deployment steps.

**Comment by budzworthy** [comment]
I wouldn't suggest to customers that they turn on the dynamic unsafe option, but maybe we can add better details on how to add the ID's of the configs they want to work with.

**Comment by budzworthy** [comment]
This is complete with the ini file architecture
