### ISSUE TITLE
Series not working correctly in demo config

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/ott-web-app#137]
Some series features don't work properly anymore in the current state. This is due to data not being configured in the app config and @dbudzins also suspects that there are some code-specific problems.

I haven't looked into this myself but created this ticket for reference.

To prevent issues when data get updated in the demo property, we should migrate the demo configs.

Probably having a separate property for e2e testing so that the data (media items, series, playlists) becomes more stable and a demo property with different app configs to use for app previews and development.

The DRM and URL Signing demos also still need separate properties since these are property-wide settings.

**Comment by marcovandeveen** [comment]
This is solved
