### ISSUE TITLE
Content hub support

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#151]
Use case: show multiple shelves belonging to specific composer, orchestra, venue, etc.

## Suggestion Solution
`contentType=hub` on media item will: 
- hide the player
- show full poster screen
- show playlists from parameter `playlists`

**Comment by budzworthy** [comment]
This is a cool, easy solution for 'static' content.  Is 'hub' an industry term? If not, maybe something like 'page' or 'text' would be even more intuitive?
