### ISSUE TITLE
Demo EPG doesn't work - 404

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#181]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/42120041/195409472-d44eb407-e108-4c99-8194-d20eb9238998.png">

**Comment by budzworthy** [comment]
@marcovandeveen I don't think this is still a problem. There was a bad deploy on October 12 as a result of us reorganizing some files for the sake of the build bundling, which I'm guessing was to blame here.  Closing the issue, but feel free to reopen if I've missed something.
