### ISSUE TITLE
Corrupt styling when refreshing video

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#194]
1. Play video
2. Hit refresh or copy-paste URL in other tab
3. Result below

Example link
https://app-preview.jwplayer.com/m/8pN9r7vd/elephants-dream?play=1&app-config=ajs7jdfk

<img width="913" alt="image" src="https://user-images.githubusercontent.com/42120041/202704092-b418b2fa-a18b-4d2a-b9e9-2fd18dd67352.png">

**Comment by budzworthy** [comment]
This should be fixed with the player changes
