### ISSUE TITLE
Remove Deprecated App Config Properties

### ISSUE THREAD

**Issue by budzworthy** [jwplayer/ott-web-app#213]
We have deprecated app config properties that don’t make sense with the approach for it to be content-only, not including any appearance or app specific settings.

Remove the following from App Config:
- Sharing
- Casting
- Player

And replace them as follows:
- Replace Sharing with a custom param
- Replace Casting with a custom param
- Replace Player with a compile time parameter defaulted to M4qoGvUk which is the OTT shared player.

Please also update documentation and e2e tests as part of this work.

**Comment by marcovandeveen** [comment]
Make sure the web app analytics pings keep referring to the proper analytics ids.

We have two 'pings':
- OTT pings
- Web player pings
