### ISSUE TITLE
Fix Player initialization issues

### ISSUE THREAD

**Issue by budzworthy** [jwplayer/ott-web-app#214]
The player initialization currently has some issues, including missing params and unsupported defaults. We need to make sure the setup is done with the following properties:

- Set the ad schedule from the `adSchedule` value in the app config
- Set casting from a custom param in the app config: `webapp.enableCasting`
- Set sharing from a custom param in the app config: `webapp.enableSharing`
  - Only support link sharing at the moment
  - Ensure the URL is correct
- Recommendations playlist from the app config `recommendationsPlaylist`

Otherwise defaults as follow:
```
  "autoPause": {
    "viewability": false
  },
  "autostart": false,
  "controls": true,
  "displayHeading": false,
  "displaydescription": false,
  "displaytitle": false,
  "floating": {
    "mode": "never"
  },
  "mute": false,
  "pipIcon": "disabled",
  "playbackRateControls": true,
  "related": {
    "autoplaytimer": 0,
    "displayMode": "shelf",
    "oncomplete": "autoplay"
  },
  "repeat": false,
  "stretching": "uniform",
  "width": "100%"
```

**Comment by AntonLantukh** [comment]
@dbudzins one comment here: we decided to remove `enableCasting` completely, so I will only add `enableSharing`.

**Comment by marcovandeveen** [comment]
Recommendations shouldn't be at player level. Just at app level as a "related videos' list
