### ISSUE TITLE
VOD DRM Support

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#23]
Many OTT implementations have licensed content, which comes with the obligation to apply DRM .

## Scope
- Studio DRM with JW Platform for VOD content 
- Update the features docs on video protection located at /docs/features
- JW platform 
- DRM policy 'low' (see [here](https://developer.jwplayer.com/jwplayer/docs/studio-drm-with-jw-platform-policy-reference#default-drm-policies) ), but with 'Max video resolution width': 3840 pixels. 

## Out-of-scope
- Opensource a URL signing solution
- DRM for Vualto Live streams
- DRM for other platforms

## JW Implementation steps
1.  Upload media to a DRM enabled property
2. Implement URL signing
3. Have the mobile and TV applications call the JW Delivery API. 

Detailed information can be found here:
- https://developer.jwplayer.com/jwplayer/docs/studio-drm-getting-started
- https://developer.jwplayer.com/jwplayer/docs/studio-drm-web-protect-your-content-with-studio-drm-with-stream
- https://developer.jwplayer.com/jwplayer/docs/studio-drm-web-protect-your-content-with-studio-drm-with-stream#intermediary-service
 
## Notes
- Testing Apple FairPlay on Safari requires Fairplay credentials. This process should be started at least 2 weeks before the start of implementation. 
- GET /v2/playlists/{playlist_id} doesn't work - Signing 
- Trailer needs to marked as `trailer` as these are freely accessible
- Chromecast doesn't work. Needs custom receiver

**Comment by marcovandeveen** [comment]
Need to check if the GET Playlist endpoint still works when DRM is enabled.

**Comment by askolodny** [comment]
@marcovandeveen now that the Studio DRM docs have been updated the following should be used: https://developer.jwplayer.com/jwplayer/docs/studio-drm-getting-started
https://developer.jwplayer.com/jwplayer/docs/studio-drm-web-protect-your-content-with-studio-drm-with-stream

Here is a guide on how to handle multi-item playlists: https://developer.jwplayer.com/jwplayer/docs/studio-drm-web-protect-your-content-with-studio-drm-with-stream#intermediary-service

@somerobmitchell is also working on a Chromecast custom receiver example with the web player

**Comment by marcovandeveen** [comment]
Awesome. Linked the new docs.

**Comment by baukef** [comment]
@somerobmitchell is the Chromecast custom receiver available for us to test?

**Comment by somerobmitchell** [comment]
@baukef No and I doubt it will be ready for a while yet. It is being worked on as a lower priority at the moment when I have time spare.
