### ISSUE TITLE
Cleeng TVOD support

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#25]
TVOD is the opposite of SVOD. Rather than giving viewers access to a broad content catalog, content owners would give them access to a single piece of content. It's was a way to monetize popular premium content and recent new releases.
TVOD can either be purely transactional (pay for unlimited access), or it can be a rental model. 

## Scope
- TVOD only 
- TVOD titles, in an SVOD model
- TVOD with upgrade to  SVOD 

## Out-of-scope
- TVOD for (instant) live streams

## Entitlement pattern
Aligned with Applicaster approach:
- Video can be viewed using SVOD or TVOD:
  - media field: `productIds`
  - field value: `<vendor-prefix>:<productid>, ...`
  -  example: `cleeng:S916977979_NL, cleeng:S91633379_NL`
- Video can be viewed TVOD only:
  - media field: `productIds` 
  - field value: `!<vendor-prefix>:<productid>, ... ` (exclamation mark)
  - example: `!cleeng:S916977979_NL`
- Video is doesn' require 
  - media field: `free` 
  - field value:  true or empty. Note: The value doesn't matter. 
  - example: `!cleeng:S916977979_NL`
- Cleeng vendor-prefix: `cleeng`

## Details
https://docs.google.com/presentation/d/1zxn-XxFYSaFr9o7YcGdm4iC17DzsmaLkswStda4zRNA/edit#slide=id.g63129a3642_0_0

## Notes
- Align with Applicaster productId
- Support SVOD as well
- Exclamation mark (!) to override global offers for premier access)
- Added: free (instead of 'requiresSubscription')

**Comment by baukef** [comment]
Could you please confirm that TVOD for live streams (including count down to live event and purchasing something that is not available to watch yet, etc) is not a requirement for this sprint?

**Comment by marcovandeveen** [comment]
Marked it as out of scope.

**Comment by ChristiaanScheermeijer** [comment]
Fixed by #66

**Comment by marcovandeveen** [comment]
Note from @ChristiaanScheermeijer 

Rearding the platform access model, we’ve stumbled upon a small issue. This is easily fixed by adding a param to the configuration, but I think it helps to explain this anyway.

We have three access models; AVOD, AUTHVOD and SVOD. The new TVOD access modal can be combined with any existing access model. Since we determine the access model based on the following conditions:
- AVOD: no cleengId/svod offers configured
- AUTHVOD: only cleengId configured
- SVOD: cleengId and svod offers configured

So when a publisher wants to support TVOD offers, a cleengId must be configured. This changes the access model to AUTHVOD, which could be valid, but I assume that the combination AVOD+TVOD will be more common (everything watchable, except TVOD items).

Since we can’t determine beforehand if a media library contains TVOD media items, I think we should move the access model to the config. The only exception is that TVOD is never an exclusive access model.
