### ISSUE TITLE
InPlayer custom register fields

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/ott-web-app#251]
InPlayer supports configuring register-fields in the dashboard. We would like to use this feature to show these custom fields in the Personal Details step just like the Cleeng integration.

Currently, the first- and lastname fields are hardcoded into the InPlayer integration making it hard to customise the registration fields for different configs.

Also important is #205, because some register fields are mandatory and should always be filled in before purchasing a subscription.

Documentation: https://client.support.inplayer.com/settings/custom-register-fields/

@kiremitrov123 @darkoatanasovski I don't see any API information regarding the custom register fields in the JS SDK or Rest APIs except for managing the fields, how should custom register fields be implemented?

**Comment by kmitrovv** [comment]
Hey @ChristiaanScheermeijer , [here](https://inplayer-org.github.io/inplayer.js/classes/Account.html#method-getRegisterFields) is a ref for the method that is responsible for the custom register fields.

By default on InPlayer side, the first and last name are merged as one (fullName). They can also be divided as separate fields, but that will open additional edge cases, so that is why it's hardcoded at this stage. 

We can easily make it to dynamically add the rest of the fields, but we should discuss it with the team and will let you know how we will proceed with this one.

**Comment by ChristiaanScheermeijer** [comment]
Hi @kiremitrov123, thanks for the information. 

I think having partly hardcoded register fields should be fine, although, a colleague mentioned that the first/last name requirement can also be disabled in the InPlayer dashboard?

Is there also documentation available on how to store the register fields in an account? I only see the `metadata` property as potential candidate for this, but I was curious how the Paywall does this.

> We can easily make it to dynamically add the rest of the fields, but we should discuss it with the team and will let you know how we will proceed with this one.

Sure, no problem. Let us know the outcome!

**Comment by marcovandeveen** [comment]
Note: Customer register fields are part of the web app but are used to capture additional consents.

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/42120041/221154753-205fa560-17b3-47d8-9d2e-e038b9129be5.png">

**Comment by kmitrovv** [comment]
The first/last name cannot be disabled, they can only be split up. By default it's `fullName` and it's stored on account level, but if someone chooses to split them up, they go into the metadata object as separate fields, same goes for the paywall.

All the extra fields can be stored only in the metadata object, there is no possibility to store them on account level.

Yes, for capturing additional consents, at the moment we use the custom register fields endpoint, where we only filter them by type `checkbox`.

**Comment by marcovandeveen** [comment]
Resolved
