### ISSUE TITLE
Static page support

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#27]
# Scope
- Add static pages for Terms and Conditions, Cookie Policy, …
- Add static page for used open-source licenses 

# Solution
- Mediaid with `contentType=page` to get the content
- Markdown to HTML transformation (client side)

<img width="613" alt="image" src="https://user-images.githubusercontent.com/42120041/190508785-78673ef9-751a-48b9-9ea4-c47f08cd7112.png">

**Comment by ChristiaanScheermeijer** [comment]
@marcovandeveen @dbudzins I see two options here

1) Create static pages using media items in the JW Dashboard
   - Using `contentType: Page` via the custom screens route
   - Title and Description fields are used for page title and markdown is parsed from description
2) Create static markdown pages in the code
   - Page is registered in a config file with a reference to the markdown file

Regarding parsing the markdown:

1) Enhance custom markdown parser
2) Using a package, I've found these candidates
   - https://www.npmjs.com/package/marked
   - https://www.npmjs.com/package/react-markdown

**Comment by ChristiaanScheermeijer** [comment]
@marcovandeveen in addition, do we also want to support links in the menu and header to static pages?
