### ISSUE TITLE
 Missing ahref attribute hinders crawler recognition (SEO)

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#291]
Search engine crawlers can't determine the link destination of cards because they do not execute JavaScript.
<img width="1302" alt="image" src="https://github.com/jwplayer/ott-web-app/assets/42120041/3e9b6da5-48d4-492e-b9a2-32766f6ecd1f">

**Comment by ChristiaanScheermeijer** [comment]
This issue is fixed by #356
