### ISSUE TITLE
Handle Cleeng externalData maxsize

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#31]
The [externalData attribute of Cleeng](https://developers.cleeng.com/reference/update-customers-data) can contain max 5000 characters. This is 50-75 objects.
So we maximize the number of history and favorite objects to 25 and rotate the oldest one out based on the 'updated' attribute

An optimized format is under discussion to ensure more items can be stored.  See [docs/features/user-watchlist.md](https://github.com/jwplayer/ott-web-app/blob/develop/docs/features/user-watchlists.md). This is possible now we have watchlist.

**Comment by marcovandeveen** [comment]
Related: https://github.com/jwplayer/ott-web-app/issues/31

**Comment by marcovandeveen** [comment]
1 History or Favorite object is about113 characters
I tried and indeed got a 400 bad requests at ~ 70 objects
Assuming having 10 favorites and watching 2 videos partially every week, happy SVOD users will reach this limit within within 35 weeks.

**Comment by AntonLantukh** [comment]
@marcovandeveen We leave only two properties for the continue_watching object and one for favorites:

**Favorites:**

```
{
    mediaId: "X88EmIbE"
}
```

Continue watching:

```
{
    mediaid: "X88EmIbE",
    progress: 0.9752381363636364
}
```

The length of one stringified object of Continue Watching equals to 52 symbols, one Favorites object equals to 22 symbols.
Taking into account only Continue Watching objects, we get 5000 / 52 = ~96, so **48** for Favorites and **48** for Continue Watching. But we can go even further and increase this value to 67 for each, if we count it as a pair (5000 / (22 + 52) = ~67. Still I think that 48 can be also enough and we will have some space for possible data structure changes.

**Comment by AntonLantukh** [comment]
Added here:

https://github.com/jwplayer/ott-web-app/pull/81
