### ISSUE TITLE
No usable config sources at Object.B1 [as queryFn] (index-306f2f52.js:1:205274)

### ISSUE THREAD

**Issue by meriseprince** [jwplayer/ott-web-app#323]
There was a problem loading the default settings. Try again later. 
No usable config sources at Object.B1 [as queryFn] (index-306f2f52.js:1:205274)

The app works fine locally but not working on firebase after build and deployment.

**Comment by budzworthy** [comment]
Conversation was resolved here: https://github.com/jwplayer/ott-web-app/issues/34#issuecomment-1607257582

Turned out to be a firebase config issue.
