### ISSUE TITLE
'Password strength score does not match standards' error is not handled by reset password form

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/ott-web-app#334]
When resetting your JWP password and entering a password with a "fair" strength, the request silently fails, and the user is not notified about the error.

The response from the reset password API is:

```json
{
    "code": 422,
    "message": "Password strength score does not match standards, please use a stronger password"
}
```

1. The error should be shown to users in the form
2. The error strength indicator should not show "fair" when not satisfying the password strength rules on the backend

**Edit**: the 'strong' and 'very strong' password strengths also fail the same restriction.

This restriction is not present when creating a new account in the registration flow.

**Comment by budzworthy** [comment]
This is due to a disconnect between the FE feedback and BE validation. Need to decide on the best way to either unify the 2 or make one more primary.

**Comment by kmitrovv** [comment]
Right, on BE we use a library for strong validation, which may have a different understanding of what constitutes 'strong' compared to the frontend. 
I believe addressing this on FE is a better approach, as modifying backend functionality could be more complex and potentially impact GDPR compliance.

**Comment by ChristiaanScheermeijer** [comment]
@kiremitrov123 I believe this issue has been solved 🎉 . Can this be closed?

**Comment by kmitrovv** [comment]
> @kiremitrov123 I believe this issue has been solved 🎉 . Can this be closed?

@ChristiaanScheermeijer Sure thing! 🎉
