### ISSUE TITLE
Release OTT App for App Config Previews

### ISSUE THREAD

**Issue by budzworthy** [jwplayer/ott-web-app#34]
On the OTT-App Config page, there is a link that allows you to preview your app config. This link essentially points to a hosted web app that can dynamically load the specific app config.

AC

Create deployment with latest version of the ott-web-app.
hosted domain app-config-preview.jwplayer.com
Make sure the app-config can be dynamically loaded based on a query param.

**Comment by marcovandeveen** [comment]
Done. See docs: https://github.com/jwplayer/ott-web-app/blob/develop/docs/configuration.md

**Comment by meriseprince** [comment]
hi, please help my app is giving this error after deployment. 

Invalid or missing settings
There was a problem loading the default settings. Try again later. If the problem persists contact technical support.

chrome console printed this error too :

Error: No usable config sources
    at Object.B1 [as queryFn] (index-306f2f52.js:1:205274)

**Comment by budzworthy** [comment]
You need to provide a default config to load: https://github.com/jwplayer/ott-web-app/blob/develop/docs/initialization-file.md

This usually comes from an App Config that you create with your JW Player account: https://docs.jwplayer.com/platform/docs/apps-app-config-overview

**Comment by meriseprince** [comment]
can i have an example files? cause i followed all these steps.
in the build/public/ files i get the .webapp.ini with theses two lines 

defaultConfigSource=xxxxxxxx
playerLicenseKey=xxxxxxxx


just like that

**Comment by budzworthy** [comment]
The config won't be created automatically, you need to do that through the JWP dashboard. Do you have a JWP account? If not, you can look at https://jwplayer.com/broadcasters/ for more information.

**Comment by meriseprince** [comment]
Hi have my account at jwplayer dashboard. i created App config and player too. account informations is set to .webapp.ini config.json url and the player ID is set inside but seem to no work

**Comment by budzworthy** [comment]
Hm, if you are using the full url for the config.json, instead try using just the ID for the config source? i.e:
`defaultConfigSource = gnnuzabk`

Also make sure the the right .ini file is being copied to the build output that you are hosting on your actual server.

**Comment by meriseprince** [comment]
yes from .webapp.prod.ini

i also tried  defaultConfigSource = gnnuzabk

defaultConfigSource=https://cdn.jwplayer.com/apps/configs/XXXXXX.json
playerLicenseKey=xxxxxxxx

or like that

defaultConfigSource = [xxxxxxxx](https://cdn.jwplayer.com/apps/configs/XXXXXX.json)
playerLicenseKey = xxxxxxxx

with space between?

its work on local with firebase emulators
but not on howting

**Comment by meriseprince** [comment]
this the firebase.json


{
  "hosting": {
    "public": "build",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "emulators": {
    "hosting": {
      "port": 5033
    },
    "ui": {
      "enabled": true
    },
    "singleProjectMode": true
  }
}

**Comment by budzworthy** [comment]
The spaces shouldn't matter. I would guess your hosting doesn't have the latest .ini file changes.

How are you deploying to firebase? Did you check that the prod ini file is also updated, not just the dev?

You can inspect the ini file being loaded by looking in the chrome network tab for a GET filtered by .webapp.ini and you'll see right away if the contents are what you expect.

**Comment by meriseprince** [comment]
<img width="1680" alt="Capture d’écran 2023-06-26 à 11 12 39 AM" src="https://github.com/jwplayer/ott-web-app/assets/34524737/d3d433dc-2b23-431f-bf57-e7273b88d8b1">

**Comment by meriseprince** [comment]
the webapp.ini is well loaded there is nothing at this point

**Comment by meriseprince** [comment]
<img width="475" alt="Capture d’écran 2023-06-26 à 11 21 58 AM" src="https://github.com/jwplayer/ott-web-app/assets/34524737/c34516af-561d-419c-b106-7166cfafbbc6">

this the content of the build folder

**Comment by budzworthy** [comment]
If you open the file from https://w...../.webapp.ini in your browser what do you see there?

**Comment by meriseprince** [comment]
Im using this command to deploy on firebase

firebase deploy --only hosting

**Comment by meriseprince** [comment]
> If you open the file from https://w...../.webapp.ini in your browser what do you see there?

not opening it make me just get back to the home url

**Comment by meriseprince** [comment]
im supposed to see the content of the file and maybe download it if i want but nothing appears expect the file link make me get back to the home url

**Comment by budzworthy** [comment]
OK, I see a couple differences in your firebase config that could be causing this:
1. `"/.*"` in the `ignore` section probably means your .webapp.ini isn't getting deployed
2. I'm not sure what `"source": ""` in `rewrites` will do. We have `"source": "**"` in ours

**Comment by meriseprince** [comment]
ok lets see

**Comment by meriseprince** [comment]
Thanks its now working super good...
Please how can i host locally my AppConfig.json?

**Comment by budzworthy** [comment]
We recommend using the config hosting through your JWP account. I can't comment on other approaches, but if you want to contact your account manager, they can help to better understand your needs. Glad it's working. Good luck!

**Comment by meriseprince** [comment]
ok thank you
