### ISSUE TITLE
Add i18next scanner

### ISSUE THREAD

**Issue by budzworthy** [jwplayer/ott-web-app#38]
It seems like i18n has been left in a half finished state. There are resource files and the translation object is used in most places, but there’s no pipeline to extract and maintain the resources. To achieve this add the scanner to the package, update the yarn commands, and add documentation:
https://github.com/i18next/i18next-scanner

**Comment by ChristiaanScheermeijer** [comment]
I think this is already implemented 😅 

https://github.com/jwplayer/ott-web-app/blob/9337f451a6020bb99d41808c46bcf03e7faa9ed3/package.json#L15

You can run the following command to extract all translations from code. 

```shell
$ yarn i18next
```

There are some quirks though when dealing with dynamic translations like `` t(`key_${variable}`) ``, you will have to define the possible translations in comments like so:

https://github.com/jwplayer/ott-web-app/blob/9337f451a6020bb99d41808c46bcf03e7faa9ed3/src/components/CheckoutForm/CheckoutForm.tsx#L59-L62
