### ISSUE TITLE
Optional label shows for playlist filters on playlist page

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [jwplayer/ott-web-app#383]
A dropdown element is shown for the tag filtering on tablet and mobile. This now shows an optional label which shouldn't be the case. 

![image](https://github.com/jwplayer/ott-web-app/assets/3996119/a88e9224-4a8d-45f9-ab91-f5de96dd4d77)

**Comment by budzworthy** [comment]
I think this is in develop, but not yet in release, correct?

I'm pretty sure this is a bug from the custom register work, which will be rolled back shortly until it's more polished. Sorry for the churn.

**Comment by ChristiaanScheermeijer** [comment]
Yes, that's right! No worries 😄

**Comment by budzworthy** [comment]
This should be resolved.
