### ISSUE TITLE
Update Cleeng integration to automatically list all subscription offers

### ISSUE THREAD

**Issue by budzworthy** [jwplayer/ott-web-app#41]
Right now, the Cleeng service requires that users hard code the yearly and monthly offer ID's in config.json. I believe it's possible for Cleeng's API to list all of the defined / enabled offers instead (see https://developers.cleeng.com/reference/listsubscriptionoffers). This will enable broadcasters to more easily manage their offers in a single place with additional flexibility beyond the 2 hardcoded ones we currently define

**Comment by ChristiaanScheermeijer** [comment]
You need the public MediaStore endpoint instead: https://developers.cleeng.com/reference/fetch-offers

Although I think publishers have more offers than they would like to list on their OTT App. Think about special offers used for marketing campaigns etc.

**Comment by budzworthy** [comment]
Ya, that makes sense. I think I wrote the original Jira version of this ticket back in Q1 when I was still learning the ott web app.  I think the offer to media item mappings probably make more sense. This ticket probably needs more grooming / thought around it before we do anything.
