### ISSUE TITLE
Have video player on video detail screen without extra click

### ISSUE THREAD

**Issue by budzworthy** [jwplayer/ott-web-app#42]
As a broadcaster, I want my viewers to see the video directly on the video detail screen so that they are more likely to watch the video

Current interaction: text only
![image](https://user-images.githubusercontent.com/7417979/164242922-9461c0d1-cd4b-4176-a90d-e2dc028e3d0b.png)

WIshed interaction: video
![image](https://user-images.githubusercontent.com/7417979/164242960-d56322c6-c016-4ff5-8632-c331b323f1f3.png)

Notes about the current design

This has been an explicit choice, to ensure Web is behaving the same as Native UIs
Adding Preview / Autoplay has a high impact on analytics. This could be the next step

**Comment by AntonLantukh** [comment]
@dbudzins maybe we should close this issue in favour of this one?
https://github.com/jwplayer/ott-web-app/issues/54

**Comment by budzworthy** [comment]
I think this task is a little bit different, but it looks like the right rail because of the example screens used.  Essentially this is referring to autoplaying videos on the detail screen behind the description (the way some platforms like Roku do.)

**Comment by marcovandeveen** [comment]
Duplicate with #54
