### ISSUE TITLE
sed: can't read build/public/.webapp.ini: No such file or directory

### ISSUE THREAD

**Issue by anoblet** [jwplayer/ott-web-app#446]
I receive this error when trying to build.

```
sed: can't read build/public/.webapp.ini: No such file or directory
```

I've copied `ini\templates\.webapp.prod.ini` to `ini\.webapp.prod.ini`, though the build command generates an empty file at `build/public/.webapp.ini` and I get this error. I even tried manually copying it to `build/public/.webapp.ini` with no success.

Any thoughts or suggestions on how I can fix this?

**Comment by budzworthy** [comment]
That's probably coming from the compress ini script: https://github.com/jwplayer/ott-web-app/blob/develop/scripts/compressIni.sh

Do you have a stacktrace? Can you tell which line the error happens on?

What command are you running to get this error? `yarn start`? `yarn build`?

**Comment by anoblet** [comment]
There's no stack trace:

![image](https://github.com/jwplayer/ott-web-app/assets/7674171/feab37f9-6c09-4997-8266-3e3a105f6dfb)

**Comment by anoblet** [comment]
I ended up using WSL without an issue.

Edit:
Make sure to change to the home directory(`cd ~`) before cloning otherwise operations are performed on the mounted filesystem which is very slow.
