### ISSUE TITLE
Inline player support

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#54]
For increased engagement a inline player (like Youtube-style) page:
- Player embedded on the movie page
- Related/next videos to the right
- Description in the bottom
- Possible to go fullscreen
- Autoplay 

Solution
 - Designs: See below and [Figma](https://www.figma.com/file/hDp7tVv98McKZPs0NLAj2N/V1.2-EPG?node-id=2864%3A177024) (Password: [here](https://jwplayer.slack.com/archives/C01PL0MENQM/p1660141372167779))
- Customer workflow: 
  - Set `inlinePlayer:true` in app config
  - Enable 'autoplay' on the configured player 

Related
- https://github.com/jwplayer/ott-web-app/issues/54    
- https://github.com/jwplayer/ott-web-app/issues/89    

<img width="463" alt="image" src="https://user-images.githubusercontent.com/42120041/191287693-bdc768cf-f04c-4a6c-a162-d2bc0cfeef0e.png">

<img width="471" alt="image" src="https://user-images.githubusercontent.com/42120041/191287719-ae71fda2-9f4f-455f-8dcb-a185e2f4c2a5.png">

<img width="463" alt="image" src="https://user-images.githubusercontent.com/42120041/191287821-6353ceb3-572e-44da-a20b-b42cfd85498a.png">

<img width="469" alt="image" src="https://user-images.githubusercontent.com/42120041/191287738-62c270e9-8e8b-45c5-836b-abb20733e48d.png">

**Comment by ChristiaanScheermeijer** [comment]
Merged to develop!
