### ISSUE TITLE
Address DRM entitlement issues

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#92]
- Stop using DRM playlist endpoints when browsing the apps

Prerequisite: Open access to playlist in DRM properties (SERV-11233)

**Comment by marcovandeveen** [comment]
@dbudzins  This solution has been delivered by JWP platform, so this ticket can now be picked up. 

**Summary**
Apps can access playlists and media metadata without requiring each call to be signed, also for DRM properties.

Benefits:
- closes a bug anonymous users get access to all videos, as the video  sources as well as the decryption policies are returned as part of the playlist request that builds up the landing page
- reduce the load time of the landing page, as the singing is required at the moment of playback
- simplifies the overall solution: DRM works like Non-DRM

The principle we are following:

- Videos should be secured
- Metadata can be freely accessed

**Comment by budzworthy** [comment]
Migrated to internal Jira
