### ISSUE TITLE
JW Geo with URL signing / DRM enabled

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#94]
Prerequisite:  [SERV-11312](https://jwplayer.atlassian.net/browse/SERV-11312) Geoblocking override for metadata

**Comment by budzworthy** [comment]
Note: @marcovandeveen probably best practice to avoid linking to internal JW Jira tickets, so people don't need / want to poke around trying to get into our proprietary company info.

**Comment by marcovandeveen** [comment]
This is delivered: there is now a standard JWP signing service, supporting geoblocking
